Develop:
  ServicePort: 0
  DebugPort: 0
  EnablePprof: false
  LogLevel: info
  ConsoleLog: true
  AgentLog: false
  FileLog: false
  EnableAccessLog: true
  EnableTracing: false
  EnableSpanLog: false
  EnableSpanMetrics: false

Product:
  ServicePort: 0
  DebugPort: 0
  EnablePprof: false
  LogLevel: info
  ConsoleLog: true
  AgentLog: false
  FileLog: false
  EnableAccessLog: true
  EnableTracing: true
  EnableSpanLog: true
  EnableSpanMetrics: true
