package extract

import (
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"
	"unicode/utf8"

	"jarvis/internal/prompttemplate"
	"jarvis/internal/sharedmem"
)

type PromptOptions struct {
	InitiativeLevel string
	PrincipalOpenID string
	Location        *time.Location
	MaxChars        int
	// AllowSingleNewOverLimit preserves one complete atomic message after every
	// removable context message has been dropped. The limit is a coarse batching
	// boundary, not permission to truncate raw evidence or strand one message
	// forever behind an unchanged watermark.
	AllowSingleNewOverLimit bool
	// SystemPrompt is the human-editable M3 role and behavior prompt.
	SystemPrompt string
	// ToolCatalog is generated by the tool layer for agent-style engines. It is
	// empty for engines whose function tools are already described by schemas.
	ToolCatalog string
	// WorkRules 是已按 extract 阶段过滤并渲染好的可信工作规则 block。
	WorkRules string
	// SharedMemory is the same trusted global block M5 and chat receive.
	SharedMemory string
	// Skills 是已按 extract 阶段过滤的简短 Skill 目录。
	Skills string
}

var ErrPromptTooLarge = errors.New("extract prompt too large")

// outputContract closes the user prompt. It sits last on purpose: by the time
// the model finishes minutes of tool calls, an instruction from the middle of
// the system prompt is far behind it, and it drifts back into chat prose. The
// worked example matters as much as the rules — models copy shapes more
// reliably than they follow prose.
const outputContract = `

=========================  输出格式（最重要，最后再读一遍）  =========================

你的最后一条消息**必须是且只能是一个 JSON 对象**，从 { 开始，到 } 结束。

- 不要写任何开场白、说明、总结或结束语；
- 不要包 ` + "```json" + ` 代码围栏；
- 不要输出多个 JSON；
- 没有任何值得留下的线索时，输出 {"candidates": []}，不要用文字说明"本轮无线索"。

candidates 中每个元素的必填内容为九个字段：action_type、status、title、target、
project_hint、source_message_ids、source_quote、payload、annotation。project_hint 判断不出来时写
空字符串 ""，不要省略这个字段。
结构化输出还包含可选来源锚点 trigger_message_id：无法确定时填 null，不需要为补齐它扩大调查。

annotation 是宽松 JSON 对象编码成的字符串（注意转义双引号），无补充时写 "{}"。
annotation 只记录有出处的关联（如 delegation_id），没有关联就使用 {}。准入理由、不确定性和你的解释写在 payload 留作 M3 审计，不生成执行简报或现场改写。
trigger_message_id 仅用于“消息原文”的单一跳转入口。已有证据足以确定时，从 source_message_ids 中选一条触发事项、方便回到现场的消息；不确定可留空，不影响准入。来源入口与证据摘录各自表达，不要求 source_quote 来自这个入口；其它证据继续保留。
source_message_ids 是唯一的直接证据列表，要包含交办原文以及“这个/上述”指代的链接或事件所在消息。消息正文与背景由程序冻结，你只写说明和已有消息 ID。

完整示例（照着这个形状写）：

{
  "candidates": [
    {
      "action_type": "investigate",
      "status": "extracted",
      "title": "排查 agent-runtime 网关偶发 502",
      "target": "agent-runtime 网关 502",
      "project_hint": "agent-runtime",
      "source_message_ids": ["om_x1"],
      "trigger_message_id": "om_x1",
      "source_quote": "今天线上又出现 502 了，麻烦帮忙看一下",
      "payload": "张伟在群里直接点名让我排查，目前只知道偶发、未定位到具体服务，也没有人认领。属于需要我介入的未闭环问题。已核验：近期没有相同 Todo。不确定：是否与昨天的发布相关。",
      "annotation": "{}"
    },
    {
      "action_type": "other",
      "status": "observing",
      "title": "Bax 评测数据集本周冻结",
      "target": "Bax 评测数据集冻结时间",
      "project_hint": "",
      "source_message_ids": ["om_x2"],
      "trigger_message_id": null,
      "source_quote": "数据集这周五冻结，之后不再接收新样本",
      "payload": "李娜宣布的时间约束，由她本人负责推进，当前不需要我做什么，但会影响我后续提交样本的节奏，值得记住。",
      "annotation": "{}"
    }
  ]
}

再说一次：**只输出这个 JSON 对象本身，前后不要有任何其它字符。**
`

func BuildPrompt(batch ChatBatch, unit ConversationUnit, now time.Time, opts PromptOptions) (Prompt, error) {
	if strings.TrimSpace(opts.PrincipalOpenID) == "" {
		return Prompt{}, fmt.Errorf("extract principal open_id is empty")
	}
	if opts.Location == nil {
		return Prompt{}, fmt.Errorf("extract prompt location is nil")
	}
	if opts.MaxChars <= 0 {
		return Prompt{}, fmt.Errorf("extract prompt max chars must be positive")
	}
	if len(unit.Messages) == 0 {
		return Prompt{}, fmt.Errorf("extract conversation unit %q has no messages", unit.Key)
	}

	trimmed := unit
	trimmed.Messages = append([]MessageContext(nil), unit.Messages...)
	system, err := prompttemplate.Render(prompttemplate.StageM3, opts.SystemPrompt, opts.WorkRules, "", opts.InitiativeLevel)
	if err != nil {
		return Prompt{}, fmt.Errorf("render M3 system prompt: %w", err)
	}
	system += "\n\nPRINCIPAL_OPEN_ID=" + opts.PrincipalOpenID
	if block := sharedmem.RenderBlock(opts.SharedMemory); block != "" {
		system += "\n\n" + block
	}
	if catalog := strings.TrimSpace(opts.ToolCatalog); catalog != "" {
		system += "\n\n" + catalog
	}
	if block := strings.TrimSpace(opts.Skills); block != "" {
		system += "\n\n" + block
	}
	for {
		shown, omitted := promptMessageCoverage(unit.Messages, trimmed.Messages)
		trimmed.Coverage = mergePromptCoverage(unit.Coverage, unit, shown, omitted)
		user := renderUserPrompt(batch, trimmed, now.In(opts.Location), opts.Location) + outputContract
		chars := utf8.RuneCountInString(system) + utf8.RuneCountInString(user)
		if chars <= opts.MaxChars {
			shown := []string{}
			omitted := []string{}
			selected := map[string]bool{}
			for _, m := range trimmed.Messages {
				if !m.BodyOmitted {
					shown = append(shown, m.MessageID)
					selected[m.MessageID] = true
				}
			}
			for _, m := range unit.Messages {
				if !selected[m.MessageID] {
					omitted = append(omitted, m.MessageID)
				}
			}
			return Prompt{System: system, User: user, ShownMessageIDs: shown, OmittedMessageIDs: omitted}, nil
		}
		if countUnitNewMessages(trimmed.Messages) > 1 {
			return Prompt{}, ErrPromptTooLarge
		}
		index := firstContextIndex(trimmed.Messages)
		if index < 0 {
			changed := false
			for i := range trimmed.Messages {
				if !trimmed.Messages[i].BodyOmitted {
					trimmed.Messages[i].BodyOmitted = true
					changed = true
					break
				}
			}
			if changed {
				continue
			}
			return Prompt{}, fmt.Errorf("%w: unit=%s chars=%d exceeds max_chars=%d after removing all context messages", ErrPromptTooLarge, unit.Key, chars, opts.MaxChars)
		}
		trimmed.Messages = append(trimmed.Messages[:index], trimmed.Messages[index+1:]...)
	}
}

func promptMessageCoverage(original, displayed []MessageContext) ([]string, []string) {
	shown := []string{}
	selected := map[string]bool{}
	for _, message := range displayed {
		if !message.BodyOmitted {
			shown = append(shown, message.MessageID)
			selected[message.MessageID] = true
		}
	}
	omitted := []string{}
	for _, message := range original {
		if !selected[message.MessageID] {
			omitted = append(omitted, message.MessageID)
		}
	}
	return shown, omitted
}

func mergePromptCoverage(base json.RawMessage, unit ConversationUnit, shown, omitted []string) json.RawMessage {
	coverage := map[string]any{}
	if len(base) > 0 {
		_ = json.Unmarshal(base, &coverage)
	}
	coverage["loaded_count"] = len(unit.Messages)
	coverage["shown_message_ids"] = shown
	coverage["omitted_message_ids"] = omitted
	coverage["missing_anchors"] = unit.MissingAnchors
	raw, _ := json.Marshal(coverage)
	return raw
}

func countUnitNewMessages(messages []MessageContext) int {
	count := 0
	for _, message := range messages {
		if message.IsNew {
			count++
		}
	}
	return count
}

func renderUserPrompt(batch ChatBatch, unit ConversationUnit, now time.Time, location *time.Location) string {
	sections := []string{
		"# 当前时间\n" + now.Format(time.RFC3339) + "（时区 " + location.String() + "）",
		"# 来源会话\n" + renderGroup(batch.Group),
		"# 参与者身份\n" + renderParticipants(unit.Participants),
		"# 相关资源入口\n" + renderResources(unit.Resources),
		"# 会话记录\n" + renderConversation(unit.Messages, location),
		"# 覆盖范围\n" + string(unit.Coverage) + fmt.Sprintf("\nmissing_anchors=%q；范围外历史未展开，可按消息 ID 或时间查询。", unit.MissingAnchors),
		"# 当前世界目录（实时、有限）\n" + string(batch.WorldOverview),
	}

	return strings.Join(sections, "\n\n")
}

func renderPrincipal(principal *PrincipalContext) string {
	if principal == nil {
		return "(未设置——请在后台「我」中完善 principal 背景)"
	}
	parts := []string{fmt.Sprintf("open_id=%s name=%q", principal.OpenID, principal.Name)}
	if principal.Department != "" {
		parts = append(parts, fmt.Sprintf("department=%q", principal.Department))
	}
	if principal.Title != "" {
		parts = append(parts, fmt.Sprintf("title=%q", principal.Title))
	}
	if principal.LeaderOpenID != "" {
		parts = append(parts, fmt.Sprintf("leader_open_id=%s leader_name=%q", principal.LeaderOpenID, principal.LeaderName))
	}
	line := strings.Join(parts, " ")
	if summary := strings.TrimSpace(principal.Summary); summary != "" {
		line += "\n" + summary
	}
	return line
}

func renderOtherProjects(projects []OtherProjectContext) string {
	if len(projects) == 0 {
		return "(none)"
	}
	lines := make([]string, len(projects))
	for i, project := range projects {
		lines[i] = fmt.Sprintf("id=%d code=%q name=%q role=%s status=%s priority=%d", project.ID, project.Code, project.Name, project.Role, project.Status, project.Priority)
	}
	return strings.Join(lines, "\n")
}

func renderProject(project *ProjectContext) string {
	if project == nil {
		return "(none)"
	}
	line := fmt.Sprintf("id=%d code=%q name=%q role=%s status=%s priority=%d",
		project.ID, project.Code, project.Name, project.Role, project.Status, project.Priority)
	if summary := strings.TrimSpace(project.Summary); summary != "" {
		line += "\n" + summary
	}
	return line
}

func renderGroup(group GroupContext) string {
	return fmt.Sprintf("chat_id=%s name=%q chat_mode=%q p2p_target_type=%q peer_open_id=%q peer_name=%q project_id=%s（群配置关联，待核对本次事项归属）", group.ChatID, group.Name, group.ChatMode, group.P2PTargetType, group.PeerOpenID, group.PeerName, uint64PointerText(group.ProjectID))
}

func renderParticipants(participants []ParticipantContext) string {
	if len(participants) == 0 {
		return "(none)"
	}
	lines := make([]string, len(participants))
	for i, participant := range participants {
		line := fmt.Sprintf("open_id=%s name=%q role=%s is_leader=%t", participant.OpenID, participant.Name, participant.Role, participant.IsLeader)
		if participant.Title != "" {
			line += fmt.Sprintf(" title=%q", participant.Title)
		}
		lines[i] = line
	}
	return strings.Join(lines, "\n")
}

func renderResources(resources []ResourceContext) string {
	if len(resources) == 0 {
		return "(none)"
	}
	lines := make([]string, len(resources))
	for i, resource := range resources {
		lines[i] = fmt.Sprintf("id=%d type=%s file_key=%q minute_token=%q doc_token=%q url=%q name=%q read=get-captured-resource --id %d",
			resource.ID, resource.ResourceType, resource.FileKey, resource.MinuteToken, resource.DocToken, resource.URL, resource.Name, resource.ID)
	}
	return strings.Join(lines, "\n")
}

func renderConversation(messages []MessageContext, location *time.Location) string {
	lines := make([]string, len(messages))
	for i, message := range messages {
		kind := "context"
		if message.IsNew {
			kind = "new"
		}
		content := message.Content
		if message.BodyOmitted {
			content = fmt.Sprintf("[原文未展开，%d 字符；query-messages --message-ids %s 取得数据库 ID 后 get-message --id ID --offset N --length N]", utf8.RuneCountInString(message.Content), message.MessageID)
		}
		content = strings.ReplaceAll(content, "\n", "\n    ")
		mentions := strings.TrimSpace(string(message.Mentions))
		if mentions == "" {
			mentions = "[]"
		}
		lines[i] = fmt.Sprintf("[%s] msg_id=%s source=%s message_type=%s time=%s sender_open_id=%s is_leader=%t sender_name=%q mentions=%s sender_type=%q chat_mode=%q reply_to=%q root_id=%q thread_id=%q: %s",
			kind, message.MessageID, message.Source, message.MessageType,
			time.UnixMilli(message.CreateTime).In(location).Format(time.RFC3339),
			message.SenderOpenID, message.IsLeader, message.SenderName, mentions, message.SenderType, message.ChatMode, message.ReplyTo, message.RootID, message.ThreadID, content)
	}
	return strings.Join(lines, "\n")
}

func firstContextIndex(messages []MessageContext) int {
	for i, message := range messages {
		if !message.IsNew && !message.IsAnchor {
			return i
		}
	}
	return -1
}

func uint64PointerText(value *uint64) string {
	if value == nil {
		return "null"
	}
	return fmt.Sprintf("%d", *value)
}
