package extract

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"
	"unicode/utf8"

	"jarvis/internal/sharedmem"
)

type PromptOptions struct {
	PrincipalOpenID string
	Location        *time.Location
	MaxChars        int
	// SystemPrompt is the human-editable M3 role and behavior prompt.
	SystemPrompt string
	// ToolCatalog is generated by the tool layer for agent-style engines. It is
	// empty for engines whose function tools are already described by schemas.
	ToolCatalog string
	// SharedMemory 是可信共享记忆文本（见 internal/sharedmem）。非空时以 RenderBlock
	// 渲染后追加到 system 段末尾（受信任指令区）；为空则不注入。
	SharedMemory string
	// WorkRules 是已按 extract 阶段过滤并渲染好的可信工作规则 block。
	WorkRules string
	// Skills 是已按 extract 阶段过滤的简短 Skill 目录。
	Skills string
}

func BuildPrompt(batch ChatBatch, unit ConversationUnit, memories []map[string]any, now time.Time, opts PromptOptions) (Prompt, error) {
	if strings.TrimSpace(opts.PrincipalOpenID) == "" {
		return Prompt{}, fmt.Errorf("extract principal open_id is empty")
	}
	if opts.Location == nil {
		return Prompt{}, fmt.Errorf("extract prompt location is nil")
	}
	if opts.MaxChars <= 0 {
		return Prompt{}, fmt.Errorf("extract prompt max chars must be positive")
	}
	if len(unit.Messages) == 0 {
		return Prompt{}, fmt.Errorf("extract conversation unit %q has no messages", unit.Key)
	}

	trimmed := unit
	trimmed.Messages = append([]MessageContext(nil), unit.Messages...)
	system := strings.TrimSpace(opts.SystemPrompt)
	system += "\n\nPRINCIPAL_OPEN_ID=" + opts.PrincipalOpenID
	if catalog := strings.TrimSpace(opts.ToolCatalog); catalog != "" {
		system += "\n\n" + catalog
	}
	if block := sharedmem.RenderBlock(opts.SharedMemory); block != "" {
		system += "\n\n" + block
	}
	if block := strings.TrimSpace(opts.WorkRules); block != "" {
		system += "\n\n" + block
	}
	if block := strings.TrimSpace(opts.Skills); block != "" {
		system += "\n\n" + block
	}
	filteredMemories := filterMemories(memories)
	for i, item := range filteredMemories {
		if _, err := json.Marshal(item); err != nil {
			return Prompt{}, fmt.Errorf("encode extraction memory index=%d: %w", i, err)
		}
	}
	for {
		user := renderUserPrompt(batch, trimmed, filteredMemories, now.In(opts.Location), opts.Location)
		if utf8.RuneCountInString(system)+utf8.RuneCountInString(user) <= opts.MaxChars {
			return Prompt{System: system, User: user}, nil
		}
		index := firstContextIndex(trimmed.Messages)
		if index < 0 {
			return Prompt{}, fmt.Errorf("extract prompt unit=%s exceeds max_chars=%d after removing all context messages", unit.Key, opts.MaxChars)
		}
		trimmed.Messages = append(trimmed.Messages[:index], trimmed.Messages[index+1:]...)
	}
}

// salientQueryMaxMessages caps how many of the most recent extractable [new]
// messages feed the memory-retrieval query. Concatenating the whole unit makes
// the query long and noisy, hurting recall; the latest messages carry the
// actionable intent, so only the last N are used.
const salientQueryMaxMessages = 20
const salientQueryMaxChars = 6000

func SalientQuery(unit ConversationUnit) (string, error) {
	parts := make([]string, 0)
	for _, message := range unit.Messages {
		if message.IsNew && message.Extractable {
			content := strings.TrimSpace(message.Content)
			if content != "" {
				parts = append(parts, content)
			}
		}
	}
	if len(parts) == 0 {
		return "", fmt.Errorf("extract conversation unit %q has no extractable new messages", unit.Key)
	}
	if len(parts) > salientQueryMaxMessages {
		parts = parts[len(parts)-salientQueryMaxMessages:]
	}
	query := strings.Join(parts, "\n")
	runes := []rune(query)
	if len(runes) <= salientQueryMaxChars {
		return query, nil
	}
	const marker = "\n...[记忆检索查询已截断]...\n"
	markerRunes := []rune(marker)
	available := salientQueryMaxChars - len(markerRunes)
	head := available / 2
	tail := available - head
	return string(runes[:head]) + marker + string(runes[len(runes)-tail:]), nil
}

func renderUserPrompt(batch ChatBatch, unit ConversationUnit, memories []map[string]any, now time.Time, location *time.Location) string {
	sections := []string{
		"# 当前时间\n" + now.Format(time.RFC3339) + "（时区 " + location.String() + "）",
		"# 我的背景(principal)\n" + renderPrincipal(batch.Principal),
		"# 当前会话所属项目（详细）\n" + renderProject(batch.Project),
		"# 我的其他项目（精简，仅作归属参考）\n" + renderOtherProjects(batch.OtherProjects),
		"# 来源会话（Group）\n" + fmt.Sprintf("chat_id=%s name=%q is_key_group=%t project_id=%s", batch.Group.ChatID, batch.Group.Name, batch.Group.IsKeyGroup, uint64PointerText(batch.Group.ProjectID)),
		"# 参与者\n" + renderParticipants(unit.Participants),
		"# 相关资源\n" + renderResources(unit.Resources),
		"# 相关记忆（仅作背景）\n" + renderMemories(memories),
		"# 已存在的未闭环 Todo（仅作背景）\n" + renderOpenTodos(batch.OpenTodos),
		"# 会话记录\n" + renderConversation(unit.Messages, location),
	}
	return strings.Join(sections, "\n\n")
}

func renderPrincipal(principal *PrincipalContext) string {
	if principal == nil {
		return "(未设置——请在后台「我」中完善决策主体背景)"
	}
	parts := []string{fmt.Sprintf("open_id=%s name=%q", principal.OpenID, principal.Name)}
	if principal.Department != "" {
		parts = append(parts, fmt.Sprintf("department=%q", principal.Department))
	}
	if principal.Title != "" {
		parts = append(parts, fmt.Sprintf("title=%q", principal.Title))
	}
	if principal.LeaderOpenID != "" {
		parts = append(parts, fmt.Sprintf("leader_open_id=%s leader_name=%q", principal.LeaderOpenID, principal.LeaderName))
	}
	line := strings.Join(parts, " ")
	if principal.Background != "" {
		line += "\n负责方向/背景：" + principal.Background
	}
	if principal.Preferences != "" {
		line += "\n喜好/工作偏好：" + principal.Preferences
	}
	return line
}

func renderOtherProjects(projects []OtherProjectContext) string {
	if len(projects) == 0 {
		return "(none)"
	}
	lines := make([]string, len(projects))
	for i, project := range projects {
		line := fmt.Sprintf("id=%d code=%q name=%q role=%s", project.ID, project.Code, project.Name, project.Role)
		if project.Description != "" {
			line += fmt.Sprintf(" desc=%q", project.Description)
		}
		lines[i] = line
	}
	return strings.Join(lines, "\n")
}

func renderProject(project *ProjectContext) string {
	if project == nil {
		return "(none)"
	}
	return fmt.Sprintf("id=%d code=%q name=%q role=%s description=%q repos=%s key_decisions=%s",
		project.ID, project.Code, project.Name, project.Role, project.Description, jsonOrNull(project.Repos), jsonOrNull(project.KeyDecisions))
}

func renderParticipants(participants []ParticipantContext) string {
	if len(participants) == 0 {
		return "(none)"
	}
	lines := make([]string, len(participants))
	for i, participant := range participants {
		line := fmt.Sprintf("open_id=%s name=%q role=%s is_leader=%t", participant.OpenID, participant.Name, participant.Role, participant.IsLeader)
		if participant.Relation != "" {
			line += fmt.Sprintf(" relation=%q", participant.Relation)
		}
		if participant.CommStyle != "" {
			line += fmt.Sprintf(" comm_style=%q", participant.CommStyle)
		}
		lines[i] = line
	}
	return strings.Join(lines, "\n")
}

func renderResources(resources []ResourceContext) string {
	if len(resources) == 0 {
		return "(none)"
	}
	lines := make([]string, len(resources))
	for i, resource := range resources {
		lines[i] = fmt.Sprintf("id=%d type=%s file_key=%q minute_token=%q doc_token=%q url=%q name=%q extracted_text=%q",
			resource.ID, resource.ResourceType, resource.FileKey, resource.MinuteToken, resource.DocToken, resource.URL, resource.Name, resource.ExtractedText)
	}
	return strings.Join(lines, "\n")
}

func renderMemories(memories []map[string]any) string {
	if len(memories) == 0 {
		return "(none)"
	}
	lines := make([]string, 0, len(memories))
	for _, item := range memories {
		encoded, err := json.Marshal(item)
		if err != nil {
			lines = append(lines, fmt.Sprintf("(invalid memory: %v)", err))
			continue
		}
		lines = append(lines, string(encoded))
	}
	return strings.Join(lines, "\n")
}

func renderOpenTodos(todos []OpenTodoContext) string {
	if len(todos) == 0 {
		return "(none)"
	}
	lines := make([]string, len(todos))
	for i, todo := range todos {
		lines[i] = fmt.Sprintf("todo_id=%d action_type=%s title=%q status=%s", todo.ID, todo.ActionType, todo.Title, todo.Status)
	}
	return strings.Join(lines, "\n")
}

func renderConversation(messages []MessageContext, location *time.Location) string {
	lines := make([]string, len(messages))
	for i, message := range messages {
		kind := "context"
		if message.IsNew {
			kind = "new"
		}
		content := strings.ReplaceAll(strings.TrimSpace(message.Content), "\r\n", "\n")
		content = strings.ReplaceAll(content, "\n", "\n    ")
		lines[i] = fmt.Sprintf("[%s] msg_id=%s source=%s time=%s sender_open_id=%s is_leader=%t sender_name=%q: %s",
			kind, message.MessageID, message.Source, time.UnixMilli(message.CreateTime).In(location).Format(time.RFC3339),
			message.SenderOpenID, message.IsLeader, message.SenderName, content)
	}
	return strings.Join(lines, "\n")
}

func filterMemories(memories []map[string]any) []map[string]any {
	return FilterMemoriesForSnapshot(memories)
}

// FilterMemoriesForSnapshot drops M3's own memories (metadata.source == "m3") so
// neither the prompt nor the frozen context_snapshot self-reinforces.
func FilterMemoriesForSnapshot(memories []map[string]any) []map[string]any {
	result := make([]map[string]any, 0, len(memories))
	for _, item := range memories {
		metadata, _ := item["metadata"].(map[string]any)
		if source, _ := metadata["source"].(string); source == "m3" {
			continue
		}
		result = append(result, item)
	}
	return result
}

func firstContextIndex(messages []MessageContext) int {
	for i, message := range messages {
		if !message.IsNew {
			return i
		}
	}
	return -1
}

func jsonOrNull(value []byte) string {
	if len(value) == 0 {
		return "null"
	}
	return string(value)
}

func uint64PointerText(value *uint64) string {
	if value == nil {
		return "null"
	}
	return fmt.Sprintf("%d", *value)
}
