#!/bin/sh
set -eu

input=""
output=""
width=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    -o)
      output="$2"
      shift 2
      ;;
    -w)
      width="$2"
      shift 2
      ;;
    *)
      input="$1"
      shift
      ;;
  esac
done

if [ -z "$input" ] || [ -z "$output" ]; then
  echo "usage: rsvg-convert [-w width] input.svg -o output.png" >&2
  exit 2
fi

NODE_PATH="/Users/bytedance/workspace-local/node_modules" node - "$input" "$output" "$width" <<'NODE'
const sharp = require('sharp');
const [input, output, width] = process.argv.slice(2);
let image = sharp(input, { density: 144 });
if (width) image = image.resize({ width: Number(width) });
image.png().toFile(output).catch((error) => {
  console.error(error);
  process.exit(1);
});
NODE
