import assert from 'node:assert/strict'

const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
const base = process.env.OKR_BROWSER_URL
const backend = process.env.OKR_TEST_API
assert(base && backend, 'Run through TestOKRBrowserWorkflow with OKR_BROWSER_URL set')
const browser = await chromium.launch({ executablePath: process.env.CHROME_EXECUTABLE, headless: true, args: ['--no-sandbox'] })
const context = await browser.newContext({ viewport: { width: 1500, height: 1100 }, permissions: ['clipboard-read', 'clipboard-write'] })
const page = await context.newPage()
page.setDefaultTimeout(12000)
const errors = [], requests = [], checks = []
const tasks = new Map(), schedules = new Map()
let nextID = 1, expectedError = false
const promptKeys = ['weekly_reminder', 'progress_sync', 'report_c', 'report_b', 'plan_review', 'progress_review']
const prompts = promptKeys.map(key => ({ key: `okr_agent_${key}`, stage: 'okr_agent', kind: 'system_prompt', name: key, content: `Test prompt ${key}`, description: `Regression ${key}` }))
page.on('pageerror', error => errors.push(error.message))
await context.route('https://example.test/**', route => route.fulfill({ body: 'Isolated external destination' }))
await context.route('**/okr-assets/**', async route => {
  const response = await fetch(backend + new URL(route.request().url()).pathname)
  await route.fulfill({ status: response.status, contentType: response.headers.get('content-type'), body: Buffer.from(await response.arrayBuffer()) })
})
await context.route('**/api/**', async route => {
  const request = route.request(), url = new URL(request.url()), path = url.pathname, method = request.method()
  requests.push({ method, path })
  const ok = data => route.fulfill({ json: { code: 0, data } })
  if (/^\/api\/(okr|biz-okr)\//.test(path) || path === '/api/people/search') {
    const response = await fetch(backend + path + url.search, { method, headers: { 'content-type': request.headers()['content-type'] || 'application/json' }, body: method === 'GET' ? undefined : request.postDataBuffer() })
    const body = await response.text()
    if (!response.ok && !expectedError) errors.push(`${method} ${path}: ${response.status} ${body}`)
    return route.fulfill({ status: response.status, contentType: 'application/json', body })
  }
  if (path === '/api/auth/status') return ok({ enabled: true, status: 'unauthenticated' })
  if (path === '/api/setup/bootstrap') return ok({ machine_configuration_ready: true })
  if (path === '/api/setup/status') return ok({ onboarding_required: false, runtime_id: 'okr-regression', app_ready: true, world_model_ready: true, configuration: { machine_configuration_ready: true, agent_name_configured: true }, lark: { available: true, app_id: 'cli_regression', credential_available: true, application_checks: [], bot: { status: 'ready', verified: true }, user: { status: 'ready', verified: true } }, agent: { available: true, authenticated: true } })
  if (path === '/api/agent-identity') return ok({ display_name: 'Regression' })
  if (path === '/api/app-modules') return ok({ items: ['okr', 'biz-okr'].map(key => ({ key, is_enabled: true })) })
  if (path === '/api/web-config') return ok({ public_base_url: base })
  if (path === '/api/text-files') return ok({ items: prompts })
  if (path.startsWith('/api/text-files/') && method === 'PUT') {
    const prompt = prompts.find(item => item.key === path.split('/').pop())
    assert(prompt)
    Object.assign(prompt, request.postDataJSON())
    return ok(prompt)
  }
  if (path === '/api/scheduled-tasks') {
    if (method === 'GET') return ok({ items: [...schedules.values()] })
    const schedule = { ...request.postDataJSON(), id: nextID++, status: 'pending', next_run_at: '2026-09-14T01:00:00Z', version: 1, dispatch_kind: 'create_task' }
    schedules.set(schedule.id, schedule)
    return ok(schedule)
  }
  if (/^\/api\/scheduled-tasks\/\d+$/.test(path)) {
    const id = Number(path.split('/').pop()), schedule = schedules.get(id)
    assert(schedule)
    if (method === 'DELETE') { schedules.delete(id); return ok({ deleted: true }) }
    if (method === 'PUT') Object.assign(schedule, request.postDataJSON(), { version: schedule.version + 1 })
    return ok(schedule)
  }
  if (path === '/api/tasks' && method === 'POST') {
    const task = { ...request.postDataJSON(), id: nextID++, status: 'pending', version: 1 }
    tasks.set(task.id, task)
    return ok(task)
  }
  if (/^\/api\/tasks\/\d+(\/execute)?$/.test(path)) {
    const task = tasks.get(Number(path.split('/')[3]))
    assert(task)
    if (path.endsWith('/execute')) { task.status = 'done'; task.execution_result = { summary: 'Isolated execution completed' }; return ok({ task }) }
    return ok(task)
  }
  errors.push(`Unexpected API: ${method} ${path}`)
  return route.fulfill({ status: 500, json: { code: 500, msg: `Unexpected API: ${path}` } })
})
const api = async (path, method = 'GET', body) => {
  const response = await fetch(backend + path, { method, headers: { 'content-type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) })
  const data = await response.json()
  assert(response.ok, `${method} ${path}: ${JSON.stringify(data)}`)
  return data.data
}
const write = async (path, action, status = 200) => {
  const waiting = page.waitForResponse(response => new URL(response.url()).pathname === path && response.request().method() !== 'GET')
  await action()
  const response = await waiting
  const body = await response.json()
  assert.equal(response.status(), status, JSON.stringify(body))
  return body.data
}
const go = async hash => {
  await page.goto(`${base}/#${hash}`)
  await page.reload()
  await page.locator('#okr-workspace-root h1').waitFor()
}
const pass = text => { checks.push(text); console.log('PASS:', text) }
const board = (week = '2026-W36') => api(`/api/biz-okr/board?quarter=2026-Q3&week=${week}`)
let planID, objectiveID
try {
  if (process.env.OKR_BROWSER_EXPORT_ONLY === '1') {
    for (const [tab, week, button] of [['review-meeting', '2026-W36', '导出 OKR Review'], ['weekly-meeting', '2026-W35', '导出全部 OKR']]) {
      await go(`/biz-okr?tab=${tab}&quarter=2026-Q3&week=${week}`)
      const result = await write('/api/biz-okr/feishu-documents', () => page.getByRole('button', { name: button, exact: true }).click(), 201)
      assert.equal(result.document_id, 'regression-document')
      assert.equal(await page.getByRole('link', { name: '打开文档', exact: true }).getAttribute('href'), result.url)
      await page.getByText('飞书文档已生成。', { exact: true }).waitFor()
    }
    await context.route('**/api/biz-okr/feishu-documents', route => route.fulfill({ status: 401, json: { code: 40181, msg: '飞书授权已失效，请退出并重新登录后再导出' } }))
    await write('/api/biz-okr/feishu-documents', () => page.getByRole('button', { name: '导出全部 OKR', exact: true }).click(), 401)
    await page.getByText('飞书授权已失效，请退出并重新登录后再导出', { exact: true }).waitFor()
    assert.equal(await page.getByRole('link', { name: '打开文档', exact: true }).count(), 0)
    assert.equal(await page.getByRole('button', { name: '导出全部 OKR', exact: true }).isEnabled(), true)
    pass('Review and weekly export return document links; expired grant has readable feedback and allows retry')
  } else {
  const officialBefore = await api('/api/okr/board?quarter=2026-Q3')
  await go('/biz-okr?tab=okr-plan&quarter=2026-Q4')
  await page.getByRole('button', { name: '新建 Plan', exact: true }).click()
  assert.equal(await page.getByRole('button', { name: '确认新建', exact: true }).isDisabled(), true)
  await page.getByLabel('Plan 名称', { exact: true }).fill('Regression Plan')
  const plan = await write('/api/biz-okr/plans', () => page.getByRole('button', { name: '确认新建', exact: true }).click(), 201)
  planID = plan.id
  await page.getByRole('button', { name: '+ 新建 O', exact: true }).click()
  await page.getByLabel('目标名称', { exact: true }).fill('测试增长目标')
  const withObjective = await write(`/api/biz-okr/plans/${planID}/objectives`, () => page.getByRole('button', { name: '创建目标', exact: true }).click(), 201)
  objectiveID = withObjective.objectives[0].id
  const objectivePath = `/api/biz-okr/plans/${planID}/objectives/${objectiveID}`
  await page.getByRole('button', { name: '+ 新建 KR', exact: true }).click()
  await page.getByPlaceholder('填写新 KR 内容').fill('提高转化率')
  await page.getByLabel('新 KR 业务分类', { exact: true }).fill('增长')
  await page.getByRole('button', { name: '确定', exact: true }).click()
  await write(objectivePath, () => page.getByRole('button', { name: '创建', exact: true }).click())
  await write(objectivePath, () => page.getByLabel('KR 内容', { exact: true }).fill('提高有效转化率'))
  await write(objectivePath, () => page.getByLabel('优先级标签', { exact: true }).selectOption('p0'))
  await page.getByRole('button', { name: '+ 添加标签', exact: true }).first().click()
  await page.getByPlaceholder('标签值').fill('回归标签')
  await write(objectivePath, () => page.getByRole('button', { name: '添加', exact: true }).click())
  const planNow = await api(`/api/biz-okr/plans/${planID}`)
  assert.equal(planNow.objectives[0].krs[0].title, '提高有效转化率')
  assert(planNow.objectives[0].krs[0].tags.some(tag => tag.value === '回归标签'))
  await page.reload()
  await page.getByLabel('选择 Plan', { exact: true }).selectOption(planID)
  assert.equal(await page.getByLabel('KR 内容', { exact: true }).inputValue(), '提高有效转化率')
  await page.locator('span[title="自定义 · 回归标签"]').waitFor()
  assert.equal(await page.locator('select[aria-label="业务分类"], input[aria-label="业务分类"]').count(), 0)
  pass('Plan create, O/KR create, title/priority/tag autosave, reload persistence')

  await page.getByRole('button', { name: '管理关联人', exact: true }).first().click()
  await page.getByPlaceholder('输入姓名或邮箱搜索').fill('Regression')
  await write(objectivePath, () => page.getByRole('button', { name: /Regression Owner.*owner@example.test/ }).click())
  await write(objectivePath, () => page.getByRole('button', { name: '例：Q3 累计自然入驻 1,253 家，线索到入驻转化率 16.51%', exact: true }).click())
  await write(objectivePath, () => page.getByPlaceholder('例：Q3 累计自然入驻 1,253 家，线索到入驻转化率 16.51%').fill('Plan 转化率达到 25%'))
  await write(objectivePath, () => page.getByRole('button', { name: '+ 一条核心数据', exact: true }).click())
  await write(objectivePath, () => page.getByTitle('删除这条核心数据', { exact: true }).last().click())
  await write(objectivePath, () => page.getByRole('button', { name: '+ 策略具体 KR', exact: true }).click())
  const planPoint = (await api(`/api/biz-okr/plans/${planID}`)).objectives[0].krs[0].points[0]
  const planPointPath = `/api/biz-okr/plans/${planID}/points/${planPoint.id}/definition`
  const planPointRow = page.locator(`#point-${planPoint.id}`)
  await write(planPointPath, () => planPointRow.getByPlaceholder('具体 KR 点').fill('Plan 交付策略'))
  await planPointRow.getByText('标签', { exact: true }).click()
  await planPointRow.getByRole('button', { name: '+ 要点标签', exact: true }).click()
  await planPointRow.getByPlaceholder('标签值').fill('具体 KR 标签')
  await write(planPointPath, () => planPointRow.getByRole('button', { name: '添加', exact: true }).click())
  await planPointRow.hover()
  await planPointRow.getByRole('button', { name: '+ 关联 Meego', exact: true }).click()
  await write(planPointPath, () => planPointRow.getByPlaceholder('工作项 ID').fill('regression-item'))
  await write(planPointPath, () => planPointRow.getByPlaceholder('链接（可选）').fill('https://example.test/meego/regression-item'))
  const detailedPlan = await api(`/api/biz-okr/plans/${planID}`)
  assert.equal(detailedPlan.objectives[0].krs[0].owners[0].email, 'regression@example.test')
  assert.equal(detailedPlan.objectives[0].krs[0].metrics[0].text, 'Plan 转化率达到 25%')
  assert(detailedPlan.objectives[0].krs[0].points[0].tags.some(tag => tag.value === '具体 KR 标签'))
  assert.equal(detailedPlan.objectives[0].krs[0].points[0].meego_work_item_id, 'regression-item')
  await planPointRow.getByTitle('删除这个具体 KR', { exact: true }).click()
  await write(objectivePath, () => planPointRow.getByRole('button', { name: '确认', exact: true }).click())
  assert.equal((await api(`/api/biz-okr/plans/${planID}`)).objectives[0].krs[0].points.length, 0)
  pass('Plan owner search, metric create/edit/delete, point edit/Meego association/delete')

  await page.getByRole('button', { name: '查看操作记录', exact: true }).click()
  const activity = page.getByRole('dialog')
  await activity.getByText('Regression Plan', { exact: false }).first().waitFor()
  await activity.locator('.ant-drawer-close').click()
  await activity.waitFor({ state: 'hidden' })
  pass('Persisted Plan activity is visible in the history drawer')

  await page.getByRole('button', { name: '打开全部评论', exact: true }).click()
  const comments = page.locator('aside[aria-hidden="false"]')
  const imageBytes = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jzWQAAAAASUVORK5CYII=', 'base64')
  await write('/api/okr/images', () => comments.locator('input[type="file"]').setInputFiles({ name: 'regression.png', mimeType: 'image/png', buffer: imageBytes }), 201)
  await comments.locator('img[src*="/okr-assets/"]').waitFor()
  await page.waitForFunction(() => [...document.querySelectorAll('aside[aria-hidden="false"] img[src*="/okr-assets/"]')].every(image => image.complete && image.naturalWidth > 0))
  await comments.getByPlaceholder('对当前 Plan 发表评论，输入 @ 选择提醒人…').fill('Plan 原始评论')
  await write(`/api/biz-okr/plans/${planID}/comments`, () => comments.getByRole('button', { name: '发布评论', exact: true }).click())
  await comments.getByText('Plan 原始评论', { exact: true }).waitFor()
  await comments.getByRole('button', { name: '回复', exact: true }).click()
  await comments.getByPlaceholder(/回复 Jarvis/).fill('Plan 回复内容')
  await write(`/api/biz-okr/plans/${planID}/comments`, () => comments.getByRole('button', { name: '回复', exact: true }).last().click())
  await comments.getByText('Plan 回复内容', { exact: true }).waitFor()
  const commentList = await api(`/api/biz-okr/plans/${planID}/comments`)
  const root = commentList.comments[0]
  assert.equal(root.images.length, 1)
  assert(root.images[0].url.startsWith('/okr-assets/'))
  await comments.getByRole('button', { name: '编辑', exact: true }).first().click()
  await comments.getByPlaceholder('修改评论…').fill('Plan 评论已修改')
  await write(`/api/biz-okr/comments/${root.id}`, () => comments.getByRole('button', { name: '保存', exact: true }).click())
  await comments.getByText('Plan 评论已修改', { exact: true }).waitFor()
  assert.equal((await api('/api/biz-okr/comments?quarter=2026-Q3&week=2026-W36')).comments.length, 0)
  await comments.getByRole('button', { name: '删除', exact: true }).last().click()
  const reply = (await api(`/api/biz-okr/plans/${planID}/comments`)).comments[0].replies[0]
  await write(`/api/biz-okr/comments/${reply.id}`, () => comments.getByRole('button', { name: '确认删除', exact: true }).click())
  await comments.getByRole('button', { name: '关闭评论', exact: true }).click()
  pass('Plan comment publish, reply, edit, delete and week-scope isolation')

  await page.getByRole('button', { name: '分享 Plan 页', exact: true }).click()
  await page.getByText('OKR Plan 页面链接已复制', { exact: true }).waitFor()
  const sharedURL = await page.evaluate(() => navigator.clipboard.readText())
  assert(sharedURL.startsWith(base) && sharedURL.includes('plan_id=' + planID))
  await page.getByRole('button', { name: 'AI评审', exact: true }).first().click()
  await page.getByRole('heading', { name: '隔离评审结果', exact: true }).waitFor()
  assert.deepEqual(await api('/api/okr/board?quarter=2026-Q3'), officialBefore)
  await page.goto(sharedURL)
  await page.reload()
  await page.getByLabel('KR 内容', { exact: true }).waitFor()
  assert.equal(await page.locator('.app-sider').count(), 0)
  assert.equal(await page.getByLabel('KR 内容', { exact: true }).inputValue(), '提高有效转化率')
  pass('Plan share deep link, AI review route and no changes to official OKR')

  await go('/biz-okr?tab=review-fill&quarter=2026-Q3&week=2026-W36')
  await page.getByLabel('周次', { exact: true }).waitFor()
  assert.deepEqual(await page.locator('select[aria-label="周次"] option').evaluateAll(options => options.map(option => option.value)), ['2026-W36'])
  const point = page.locator('#point-official-p')
  await point.getByRole('button', { name: '+ 一条进展', exact: true }).click()
  assert.equal(await point.getByRole('button', { name: '添加', exact: true }).isDisabled(), true)
  await point.getByPlaceholder('填写本周进展').fill('完成 60% 回归验证')
  await write('/api/okr/points/official-p/progress', () => point.getByRole('button', { name: '添加', exact: true }).click(), 201)
  let current = await board()
  let entry = current.objectives[0].krs[0].points.find(item => item.id === 'official-p').entries[0]
  await write(`/api/okr/progress/${entry.id}`, () => point.getByPlaceholder('可衡量的本周进展；无更新请写明预期更新时间').fill('完成 80% 回归验证'))
  await point.locator('.status-select-button').click()
  await write(`/api/okr/progress/${entry.id}`, () => point.getByRole('button', { name: '已完成', exact: true }).click())
  await write('/api/biz-okr/scores/kr/official-kr', () => page.getByLabel('一级 KR 评分', { exact: true }).selectOption('0.8'))
  await write('/api/biz-okr/scores/point/official-p', () => point.getByLabel('具体 KR 评分', { exact: true }).selectOption('0.7'))
  await write('/api/okr/krs/official-kr/weekly-core', () => page.getByPlaceholder('例：Q3 累计自然入驻 1,253 家，线索到入驻转化率 16.51%').fill('本周核心数据 80'))
  current = await board()
  assert.equal(current.objectives[0].krs[0].score.value, 0.8)
  assert.equal(current.objectives[0].krs[0].metrics[0].text, '本周核心数据 80')
  assert.equal((await api('/api/okr/board?quarter=2026-Q3')).objectives[0].krs[0].metrics[0].text, '正式目标 100')
  await page.reload()
  await page.getByPlaceholder('可衡量的本周进展；无更新请写明预期更新时间').waitFor()
  assert.equal(await point.getByPlaceholder('可衡量的本周进展；无更新请写明预期更新时间').inputValue(), '完成 80% 回归验证')
  pass('Review progress create/update/status, KR/point scores, weekly metrics and persistence')

  current = await board()
  entry = current.objectives[0].krs[0].points.find(item => item.id === 'official-p').entries[0]
  await api(`/api/okr/progress/${entry.id}`, 'PUT', { week: '2026-W36', text: '协作者已保存', status: entry.status, docs: entry.docs, images: entry.images, source: 'manual', expected_version: entry.version })
  expectedError = true
  await write(`/api/okr/progress/${entry.id}`, () => point.getByPlaceholder('可衡量的本周进展；无更新请写明预期更新时间').fill('我的冲突草稿'), 409)
  await page.getByRole('button', { name: '保留我的修改', exact: true }).waitFor()
  assert.equal(await point.getByPlaceholder('可衡量的本周进展；无更新请写明预期更新时间').inputValue(), '我的冲突草稿')
  expectedError = false
  await write(`/api/okr/progress/${entry.id}`, () => page.getByRole('button', { name: '保留我的修改', exact: true }).click())
  assert.equal((await board()).objectives[0].krs[0].points.find(item => item.id === 'official-p').entries[0].text, '我的冲突草稿')
  pass('Concurrent edit returns 409, retains local draft and explicit retry persists')

  const followUp = await write('/api/biz-okr/follow-ups', () => page.getByRole('button', { name: '+ 新增事项', exact: true }).click(), 201)
  const followUpPath = `/api/biz-okr/follow-ups/${followUp.id}`
  await page.getByLabel('Topic 新待跟进事项', { exact: true }).fill('跟进量化验收')
  await write(followUpPath, () => page.getByLabel('Topic 跟进量化验收', { exact: true }).blur())
  await page.getByLabel('Update 跟进量化验收', { exact: true }).fill('验收进展已记录')
  await write(followUpPath, () => page.getByLabel('Update 跟进量化验收', { exact: true }).blur())
  assert.equal((await api(followUpPath)).update, '验收进展已记录')
  await go('/biz-okr?tab=review-meeting&quarter=2026-Q3&week=2026-W36')
  await page.getByText('跟进量化验收', { exact: true }).waitFor()
  const followSelect = page.locator('tr').filter({ hasText: '跟进量化验收' }).locator('select')
  await write(followUpPath, () => followSelect.selectOption('done'))
  assert.equal(await page.getByRole('button', { name: '+ 一条进展', exact: true }).count(), 0)
  assert.equal((await api(followUpPath)).status, 'done')
  await write('/api/biz-okr/scores/kr/official-kr', () => page.getByLabel('一级 KR 评分', { exact: true }).selectOption('0.9'))
  assert.equal((await board()).objectives[0].krs[0].score.value, 0.9)
  await write('/api/biz-okr/feishu-documents', () => page.getByRole('button', { name: '导出 OKR Review', exact: true }).click(), 201)
  pass('Review meeting preserves read-only content while allowing score/follow-up updates and export')

  await go('/biz-okr?tab=weekly-fill&quarter=2026-Q3&week=2026-W35')
  await page.getByLabel('周次', { exact: true }).waitFor()
  assert.deepEqual(await page.locator('select[aria-label="周次"] option').evaluateAll(options => options.map(option => option.value)), ['2026-W35', '2026-W34'])
  assert.equal(await page.getByLabel('一级 KR 评分', { exact: true }).count(), 0)
  assert.equal(await page.getByText('我的冲突草稿', { exact: true }).count(), 0)
  await point.getByRole('button', { name: '+ 一条进展', exact: true }).click()
  await point.getByPlaceholder('填写本周进展').fill('普通周报独立进展')
  await write('/api/okr/points/official-p/progress', () => point.getByRole('button', { name: '添加', exact: true }).click(), 201)
  assert.equal((await board('2026-W36')).objectives[0].krs[0].points.find(item => item.id === 'official-p').entries[0].text, '我的冲突草稿')
  await page.getByRole('button', { name: /周报工具/ }).click()
  await page.getByRole('button', { name: /进展填写检查/ }).click()
  await page.getByText('进展填写检查', { exact: true }).last().waitFor()
  await page.getByRole('button', { name: /Meego 差异/ }).click()
  await page.getByText(/Meego/).first().waitFor()
  await page.getByRole('button', { name: '新建周报', exact: true }).click()
  await page.getByLabel('新周次', { exact: true }).fill('2026-W37')
  await write('/api/okr/weeks', () => page.getByRole('button', { name: '确认新建', exact: true }).click(), 201)
  await page.waitForFunction(() => document.querySelector('select[aria-label="周次"]')?.value === '2026-W37')
  await page.getByRole('button', { name: '删除周报', exact: true }).click()
  await write('/api/biz-okr/weeks/2026-W37', () => page.getByRole('dialog').getByRole('button', { name: /删.*除/ }).click())
  await page.waitForFunction(() => document.querySelector('select[aria-label="周次"]')?.value !== '2026-W37')
  await page.getByRole('button', { name: '新建周报', exact: true }).click()
  await page.getByLabel('新周次', { exact: true }).fill('2026-W37')
  expectedError = true
  await page.getByRole('button', { name: '确认新建', exact: true }).click()
  await page.getByText('该周次已删除，不允许重新新建', { exact: true }).waitFor()
  expectedError = false
  assert.equal((await board('2026-W35')).objectives[0].krs[0].points.find(item => item.id === 'official-p').entries[0].text, '普通周报独立进展')
  pass('Classic weekly progress, separate week catalogs, tools, open/delete and no reopening')

  await go('/biz-okr?tab=weekly-meeting&quarter=2026-Q3&week=2026-W35')
  await page.getByText('普通周报独立进展', { exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: '+ 一条进展', exact: true }).count(), 0)
  assert.equal(await page.getByLabel('一级 KR 评分', { exact: true }).count(), 0)
  await write('/api/biz-okr/feishu-documents', () => page.getByRole('button', { name: '导出全部 OKR', exact: true }).click(), 201)
  await page.getByRole('button', { name: /分享.*页/ }).click()
  await page.getByText(/页面链接已复制/).waitFor()
  const weeklyURL = await page.evaluate(() => navigator.clipboard.readText())
  assert(weeklyURL.includes('tab=weekly-meeting') && weeklyURL.includes('week=2026-W35'))
  await page.goto(weeklyURL)
  await page.reload()
  await page.getByText('普通周报独立进展', { exact: true }).waitFor()
  assert.equal(await page.locator('.app-sider').count(), 0)
  assert.equal(await page.getByRole('button', { name: /周报工具/ }).count(), 0)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '打开全部评论', exact: true }).click()
  await comments.getByPlaceholder('对本周页面发表评论，输入 @ 选择提醒人…').fill('移动端周报评论')
  await write('/api/biz-okr/comments', () => comments.getByRole('button', { name: '发布评论', exact: true }).click())
  await comments.getByText('移动端周报评论', { exact: true }).waitFor()
  assert.equal((await api('/api/biz-okr/comments?quarter=2026-Q3&week=2026-W35')).comments[0].content, '移动端周报评论')
  await comments.getByRole('button', { name: '关闭评论', exact: true }).click()
  await page.setViewportSize({ width: 1500, height: 1100 })
  pass('Classic meeting, scoped share link, mobile comments and external export contract')

  await go('/biz-okr?tab=agent-flows&quarter=2026-Q3')
  await page.getByRole('tab', { name: /通知与跟进/ }).waitFor()
  for (const category of [/通知与跟进/, /材料生成/]) {
    await page.getByRole('tab', { name: category }).click()
    for (let index = 0; index < 2; index++) {
      await page.getByRole('button', { name: '任务详情', exact: true }).nth(index).click()
      const dialog = page.getByRole('dialog')
      await dialog.locator('textarea').fill('隔离任务 Prompt')
      await dialog.getByLabel('启用自动执行', { exact: false }).uncheck()
      await dialog.getByRole('button', { name: '保存任务', exact: true }).click()
      await dialog.waitFor({ state: 'hidden' })
      await page.getByRole('button', { name: '立即运行', exact: true }).nth(index).click()
      await page.getByText('Isolated execution completed', { exact: true }).first().waitFor()
    }
  }
  assert.equal(schedules.size, 4)
  assert.equal(tasks.size, 4)
  for (const task of tasks.values()) assert.equal(task.source_payload.module, 'biz-okr')
  await page.getByRole('tab', { name: /Prompt/ }).click()
  await page.locator('textarea').fill('修改后的评审 Prompt')
  await page.getByRole('button', { name: '保存并生效', exact: true }).click()
  await page.getByText(/已保存，后续评审/).waitFor()
  assert(prompts.some(prompt => prompt.content === '修改后的评审 Prompt'))
  pass('All four Agent action settings and dispatch contracts, standalone Prompt save')

  await go(`/biz-okr?tab=okr-plan&quarter=2026-Q4&plan_id=${planID}`)
  await page.getByLabel('KR 内容', { exact: true }).waitFor()
  await page.getByRole('button', { name: '删除 Plan', exact: true }).click()
  await write(`/api/biz-okr/plans/${planID}`, () => page.getByRole('button', { name: '确认删除', exact: true }).click())
  assert(!(await api('/api/biz-okr/plans?quarter=2026-Q4')).plans.some(item => item.id === planID))
  assert.equal((await api('/api/okr/board?quarter=2026-Q3')).objectives[0].id, 'official-o')
  pass('Plan delete removes only its own draft data')

  const beforeManagement = await api('/api/okr/board?quarter=2026-Q3')
  await go('/biz-okr?tab=manage&quarter=2026-Q3')
  await page.getByRole('button', { name: '+ 新建 O', exact: true }).click()
  await page.getByLabel('目标名称', { exact: true }).fill('可删除的正式目标')
  const official = await write('/api/okr/objectives', () => page.getByRole('button', { name: '创建目标', exact: true }).click(), 201)
  const objectiveHeader = page.locator('div[id]').filter({ has: page.getByRole('heading', { name: '可删除的正式目标', exact: true }) }).last()
  await objectiveHeader.getByRole('button', { name: '+ 新建 KR', exact: true }).click()
  await page.getByPlaceholder('填写新 KR 内容').fill('新正式 KR')
  const newKR = await write(`/api/biz-okr/objectives/${official.id}/krs`, () => page.getByRole('button', { name: '创建', exact: true }).click(), 201)
  const krRow = page.locator(`article[id="comment-target-${encodeURIComponent(`kr:${newKR.id}`)}"]`)
  const krPath = `/api/biz-okr/krs/${newKR.id}`
  await write(krPath, () => krRow.getByLabel('KR 内容', { exact: true }).fill('正式 KR 已修改'))
  await write(krPath, () => krRow.getByLabel('优先级标签', { exact: true }).selectOption('p2'))
  await krRow.getByRole('button', { name: /指标与拆解/ }).click()
  await krRow.getByRole('button', { name: '例：Q3 累计自然入驻 1,253 家，线索到入驻转化率 16.51%', exact: true }).click()
  await write(krPath, () => krRow.getByPlaceholder('例：Q3 累计自然入驻 1,253 家，线索到入驻转化率 16.51%').fill('正式指标 200'))
  await krRow.getByRole('button', { name: '+ 一项', exact: true }).first().click()
  await write(krPath, () => krRow.getByPlaceholder('具体 KR 点').fill('新正式策略'))
  const createdPoint = (await api(`/api/okr/krs/${newKR.id}`)).points[0]
  const newPoint = page.locator(`#point-${createdPoint.id}`)
  await write(`/api/okr/points/${createdPoint.id}/definition`, () => newPoint.getByPlaceholder('具体 KR 点').fill('正式策略已修改'))
  await page.reload()
  await page.locator(`input[value="正式 KR 已修改"]`).waitFor()
  const persistedKR = await api(`/api/okr/krs/${newKR.id}`)
  assert.equal(persistedKR.metrics[0].text, '正式指标 200')
  assert.equal(persistedKR.points[0].title, '正式策略已修改')
  assert((await api(`/api/biz-okr/krs/${newKR.id}`)).tags.some(tag => tag.value === 'p2'))
  const restoredRow = page.locator('article').filter({ has: page.locator('input[value="正式 KR 已修改"]') })
  await restoredRow.getByTitle('删除 KR', { exact: true }).click()
  await write(`/api/okr/krs/${newKR.id}`, () => restoredRow.getByRole('button', { name: '确认', exact: true }).click())
  await page.getByRole('button', { name: '删除空 O', exact: true }).click()
  await write(`/api/okr/objectives/${official.id}`, () => page.getByRole('button', { name: '确认删除', exact: true }).click())
  assert.deepEqual(await api('/api/okr/board?quarter=2026-Q3'), beforeManagement)
  assert.equal((await board()).objectives[0].krs[0].points.find(item => item.id === 'official-p').entries[0].text, '我的冲突草稿')
  pass('Official OKR management creates/edits/deletes definitions without changing existing progress')
  }
  assert.deepEqual(errors, [])
  console.log(JSON.stringify({ result: 'passed', checks, realAPIRequests: requests.filter(request => /^\/api\/(biz-okr|okr)\//.test(request.path)).length, isolatedAgentTasks: tasks.size }))
} catch (error) {
  console.error(JSON.stringify({ checks, errors, lastRequests: requests.slice(-12), body: (await page.locator('body').innerText()).slice(-14000) }))
  throw error
} finally {
  await browser.close()
}
